import { HeroDefinition, HeroId } from '../types/game';

export const MAP_CONFIG = {
  width: 2600,
  height: 2600,
  playerRadius: 22,
  fogResolution: 360,
  flashlightDistance: 560,
  flashlightAngle: Math.PI * 0.42, // ~75 degrees default flashlight
  peripheralVisionDistance: 95,    // Immediate circle around player
  echoSoundRadius: 650,           // Distance where footsteps/gunfire echoes are heard
  maxBots: 5,
};

export const DEFAULT_PISTOL_STATS = {
  weaponName: 'B-9 Tactical Sidearm',
  fireRange: 330,
  fireAngle: (38 * Math.PI) / 180,
  bulletDamage: 34,
  bulletSpeed: 900,
  fireRate: 4.2,
  bulletSpread: 0.04,
  maxAmmo: 15,
  reloadTime: 1.0,
  color: '#94a3b8',
};

export const HERO_DEFINITIONS: Record<HeroId, HeroDefinition> = {
  // THE 4 BALANCED FIXED-CLASS OPERATIVES
  sniper: {
    id: 'sniper',
    name: 'GHOST',
    title: 'Precision Sniper',
    role: 'Sniper',
    description: 'Elite long-range precision operative armed with the V-99 Ballistic Sniper. Massive single-shot stopping power, piercing rail velocity, and acoustic thermal recon scan.',
    color: '#10b981', // Emerald
    accentColor: '#047857',
    maxHp: 780,
    maxArmor: 300,
    speed: 205,
    weaponName: 'V-99 Ballistic Sniper',
    fireRange: 640,
    fireAngle: (18 * Math.PI) / 180,
    bulletDamage: 275,
    bulletSpeed: 1450,
    fireRate: 1.2,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.012,
    pellets: 1,
    maxAmmo: 5,
    reloadTime: 2.2,
    abilityName: 'Thermal Recon Scan',
    abilityIcon: 'Zap',
    abilityDescription: 'Emits a wide acoustic thermal pulse revealing all enemy positions and footsteps on radar for 5.0 seconds.',
    abilityCooldown: 12,
    abilityDuration: 5.0,
  },
  shotgun: {
    id: 'shotgun',
    name: 'BREACHER',
    title: 'Combat Breacher',
    role: 'Shotgun',
    description: 'Devastating close-quarters breacher wielding the Bulldog 12-Gauge pump shotgun with 8 heavy scatter buckshot pellets and tactical high-explosive cluster frag grenades.',
    color: '#ef4444', // Crimson
    accentColor: '#b91c1c',
    maxHp: 960,
    maxArmor: 380,
    speed: 205,
    weaponName: 'Bulldog 12-Gauge',
    fireRange: 240,
    fireAngle: (54 * Math.PI) / 180,
    bulletDamage: 38, // 8 x 38 = 304 max point blank
    bulletSpeed: 740,
    fireRate: 1.8,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.20,
    pellets: 8,
    maxAmmo: 6,
    reloadTime: 1.8,
    abilityName: 'Cluster Frag Grenade',
    abilityIcon: 'Bomb',
    abilityDescription: 'Lobs a high-explosive fragmentation grenade dealing 350 blast damage in a 140px radius with lethal concussive knockback.',
    abilityCooldown: 11,
    abilityDuration: 0,
  },
  assault: {
    id: 'assault',
    name: 'VANGUARD',
    title: 'Tactical Commando',
    role: 'Assault',
    description: 'High-discipline assault operative armed with the M4-Spectre Assault Rifle. Balanced sustained DPS, steady mid-range accuracy, and rapid adrenaline combat stimpack.',
    color: '#38bdf8', // Sky Blue
    accentColor: '#0284c7',
    maxHp: 920,
    maxArmor: 420,
    speed: 195,
    weaponName: 'M4-Spectre Assault Rifle',
    fireRange: 430,
    fireAngle: (36 * Math.PI) / 180,
    bulletDamage: 52,
    bulletSpeed: 980,
    fireRate: 7.2,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.032,
    pellets: 1,
    maxAmmo: 30,
    reloadTime: 1.6,
    abilityName: 'Adrenaline Combat Stim',
    abilityIcon: 'Ghost',
    abilityDescription: 'Injects military combat stim restoring 140 HP instantly and granting +35% movement speed and weapon stability for 5.0 seconds.',
    abilityCooldown: 12,
    abilityDuration: 5.0,
  },
  marksman: {
    id: 'marksman',
    name: 'DEADEYE',
    title: 'Designated Marksman',
    role: 'Recon',
    description: 'Precision designated marksman fielding the semi-automatic MK-14 EBR DMR. Superior mid-to-long range armor penetration, high fire rate, and directional kinetic ballistic barrier.',
    color: '#f59e0b', // Amber Gold
    accentColor: '#b45309',
    maxHp: 860,
    maxArmor: 460,
    speed: 185,
    weaponName: 'MK-14 EBR DMR',
    fireRange: 520,
    fireAngle: (26 * Math.PI) / 180,
    bulletDamage: 92,
    bulletSpeed: 1250,
    fireRate: 3.6,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.016,
    pellets: 1,
    maxAmmo: 15,
    reloadTime: 1.7,
    abilityName: 'Kinetic Ballistic Shield',
    abilityIcon: 'ShieldAlert',
    abilityDescription: 'Deploys a forward energy barrier absorbing 75% incoming projectile damage for 5.0 seconds.',
    abilityCooldown: 13,
    abilityDuration: 5.0,
  },

  // Backwards compatibility aliases mapped to the 4 balanced archetypes
  titan: {
    id: 'titan',
    name: 'TITAN',
    title: 'Heavy Assault',
    role: 'Assault',
    description: 'Heavy assault operative armed with sustained firepower and tactical defensive barrier.',
    color: '#f59e0b',
    accentColor: '#b45309',
    maxHp: 1100,
    maxArmor: 500,
    speed: 175,
    weaponName: 'M4-Spectre Heavy',
    fireRange: 410,
    fireAngle: (40 * Math.PI) / 180,
    bulletDamage: 54,
    bulletSpeed: 920,
    fireRate: 7.0,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.04,
    pellets: 1,
    maxAmmo: 35,
    reloadTime: 1.8,
    abilityName: 'Cyber Barrier',
    abilityIcon: 'ShieldAlert',
    abilityDescription: 'Deploys a directional barrier absorbing 75% incoming damage for 5.0 seconds.',
    abilityCooldown: 13,
    abilityDuration: 5.0,
  },
  stalker: {
    id: 'stalker',
    name: 'VANGUARD',
    title: 'Tactical Commando',
    role: 'Assault',
    description: 'Frontline operative with high sustained DPS and adrenaline combat stim.',
    color: '#38bdf8',
    accentColor: '#0284c7',
    maxHp: 920,
    maxArmor: 420,
    speed: 195,
    weaponName: 'M4-Spectre Assault Rifle',
    fireRange: 430,
    fireAngle: (36 * Math.PI) / 180,
    bulletDamage: 52,
    bulletSpeed: 980,
    fireRate: 7.2,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.032,
    pellets: 1,
    maxAmmo: 30,
    reloadTime: 1.6,
    abilityName: 'Adrenaline Combat Stim',
    abilityIcon: 'Ghost',
    abilityDescription: 'Restores 140 HP and gives +35% speed for 5 seconds.',
    abilityCooldown: 12,
    abilityDuration: 5.0,
  },
  valkyrie: {
    id: 'valkyrie',
    name: 'GHOST',
    title: 'Precision Sniper',
    role: 'Sniper',
    description: 'Precision long-range sniper with acoustic thermal scan.',
    color: '#10b981',
    accentColor: '#047857',
    maxHp: 780,
    maxArmor: 300,
    speed: 205,
    weaponName: 'V-99 Ballistic Sniper',
    fireRange: 640,
    fireAngle: (18 * Math.PI) / 180,
    bulletDamage: 275,
    bulletSpeed: 1450,
    fireRate: 1.2,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.012,
    pellets: 1,
    maxAmmo: 5,
    reloadTime: 2.2,
    abilityName: 'Thermal Recon Scan',
    abilityIcon: 'Zap',
    abilityDescription: 'Reveals all enemy positions for 5 seconds.',
    abilityCooldown: 12,
    abilityDuration: 5.0,
  },
  bastion: {
    id: 'bastion',
    name: 'DEADEYE',
    title: 'Designated Marksman',
    role: 'Recon',
    description: 'Designated marksman with semi-automatic precision rifle.',
    color: '#f59e0b',
    accentColor: '#b45309',
    maxHp: 860,
    maxArmor: 460,
    speed: 185,
    weaponName: 'MK-14 EBR DMR',
    fireRange: 520,
    fireAngle: (26 * Math.PI) / 180,
    bulletDamage: 92,
    bulletSpeed: 1250,
    fireRate: 3.6,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.016,
    pellets: 1,
    maxAmmo: 15,
    reloadTime: 1.7,
    abilityName: 'Kinetic Ballistic Shield',
    abilityIcon: 'ShieldAlert',
    abilityDescription: 'Deploys a barrier absorbing 75% incoming damage for 5 seconds.',
    abilityCooldown: 13,
    abilityDuration: 5.0,
  },
  mirage: {
    id: 'mirage',
    name: 'GHOST',
    title: 'Precision Sniper',
    role: 'Sniper',
    description: 'Precision long-range sniper with acoustic thermal scan.',
    color: '#10b981',
    accentColor: '#047857',
    maxHp: 780,
    maxArmor: 300,
    speed: 205,
    weaponName: 'V-99 Ballistic Sniper',
    fireRange: 640,
    fireAngle: (18 * Math.PI) / 180,
    bulletDamage: 275,
    bulletSpeed: 1450,
    fireRate: 1.2,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.012,
    pellets: 1,
    maxAmmo: 5,
    reloadTime: 2.2,
    abilityName: 'Thermal Recon Scan',
    abilityIcon: 'Zap',
    abilityDescription: 'Reveals all enemy positions for 5 seconds.',
    abilityCooldown: 12,
    abilityDuration: 5.0,
  },
  sparkle: {
    id: 'sparkle',
    name: 'BREACHER',
    title: 'Combat Breacher',
    role: 'Shotgun',
    description: 'Close-quarters shotgun specialist with cluster frag grenade.',
    color: '#ef4444',
    accentColor: '#b91c1c',
    maxHp: 960,
    maxArmor: 380,
    speed: 205,
    weaponName: 'Bulldog 12-Gauge',
    fireRange: 240,
    fireAngle: (54 * Math.PI) / 180,
    bulletDamage: 38,
    bulletSpeed: 740,
    fireRate: 1.8,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.20,
    pellets: 8,
    maxAmmo: 6,
    reloadTime: 1.8,
    abilityName: 'Cluster Frag Grenade',
    abilityIcon: 'Bomb',
    abilityDescription: 'Lobs a high-explosive grenade dealing 350 damage.',
    abilityCooldown: 11,
    abilityDuration: 0,
  },
  firefly: {
    id: 'firefly',
    name: 'VANGUARD',
    title: 'Tactical Commando',
    role: 'Assault',
    description: 'Assault operative with high combat mobility.',
    color: '#38bdf8',
    accentColor: '#0284c7',
    maxHp: 920,
    maxArmor: 420,
    speed: 195,
    weaponName: 'M4-Spectre Assault Rifle',
    fireRange: 430,
    fireAngle: (36 * Math.PI) / 180,
    bulletDamage: 52,
    bulletSpeed: 980,
    fireRate: 7.2,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.032,
    pellets: 1,
    maxAmmo: 30,
    reloadTime: 1.6,
    abilityName: 'Adrenaline Combat Stim',
    abilityIcon: 'Ghost',
    abilityDescription: 'Restores 140 HP and +35% speed for 5s.',
    abilityCooldown: 12,
    abilityDuration: 5.0,
  },
  raven: {
    id: 'raven',
    name: 'GHOST',
    title: 'Precision Sniper',
    role: 'Sniper',
    description: 'Precision sniper scout with acoustic sonar.',
    color: '#10b981',
    accentColor: '#047857',
    maxHp: 780,
    maxArmor: 300,
    speed: 205,
    weaponName: 'V-99 Ballistic Sniper',
    fireRange: 640,
    fireAngle: (18 * Math.PI) / 180,
    bulletDamage: 275,
    bulletSpeed: 1450,
    fireRate: 1.2,
    burstCount: 1,
    burstDelay: 0,
    bulletSpread: 0.012,
    pellets: 1,
    maxAmmo: 5,
    reloadTime: 2.2,
    abilityName: 'Thermal Recon Scan',
    abilityIcon: 'Zap',
    abilityDescription: 'Reveals all enemy positions for 5 seconds.',
    abilityCooldown: 12,
    abilityDuration: 5.0,
  },
};

export const FIXED_CHARACTERS: {
  id: string;
  heroId: HeroId;
  name: string;
  role: string;
  weapon: string;
  description: string;
}[] = [
  {
    id: 'ghost',
    heroId: 'sniper',
    name: 'GHOST',
    role: 'Sniper',
    weapon: 'V-99 Ballistic Sniper',
    description: 'Long-range thermal sniper scout. High caliber precision damage with piercing ballistic velocity.',
  },
  {
    id: 'breacher',
    heroId: 'shotgun',
    name: 'BREACHER',
    role: 'Shotgun',
    weapon: 'Bulldog 12-Gauge',
    description: 'High close-quarters stopping power with 8-pellet buckshot spread and tactical cluster frag grenades.',
  },
  {
    id: 'vanguard',
    heroId: 'assault',
    name: 'VANGUARD',
    role: 'Assault',
    weapon: 'M4-Spectre AR',
    description: 'Disciplined tactical rifleman with steady full-auto fire and adrenaline stimpack health recovery.',
  },
  {
    id: 'deadeye',
    heroId: 'marksman',
    name: 'DEADEYE',
    role: 'Marksman',
    weapon: 'MK-14 EBR DMR',
    description: 'Semi-automatic designated marksman with high armor penetration and kinetic forward barrier.',
  },
];
